# Generated by Django 4.0 on 2022-03-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_type',
            name='store',
            field=models.CharField(blank=True, choices=[('Carpet Yard', 'Carpet Yard'), ('EB-Carpets & More East Brunswick', 'EB-Carpets & More East Brunswick'), ('Warehouse', 'Warehouse'), ('SI-Carpets & More Staten Island', 'SI-Carpets & More Staten Island'), ('OB-Carpets & More Old Bridge', 'OB-Carpets & More Old Bridge')], max_length=50, null=True, verbose_name='Corporation/Store'),
        ),
    ]
