# Generated by Django 4.0 on 2022-03-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_material_type_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernumbershelf',
            name='sm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.material_type'),
        ),
    ]
